[package]
name = "bomber_game"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = "0.30"
bevy = "0.5"
anyhow = "1.0"

[dependencies.bomber_lib]
path = "../bomber_lib"

